#   access_key_id: 123
#   secret_access_key: 345
github:
  test:
    id: <%= ENV["GITHUB_ID"]%>
    secret: <%= ENV["GITHUB_SECRET"]%>
  development:
    id: <%= ENV["GITHUB_ID"]%>
    secret: <%= ENV["GITHUB_SECRET"]%>
  production:
    id: <%= ENV["GITHUB_ID"]%>
    secret: <%= ENV["GITHUB_SECRET"]%>

twitter:
  test:
    id: <%= ENV["TWITTER_ID"]%>
    secret: <%= ENV["TWITTER_SECRET"]%>
  development:
    id: <%= ENV["TWITTER_ID"]%>
    secret: <%= ENV["TWITTER_SECRET"]%>
  production:
    id: <%= ENV["TWITTER_ID"]%>
    secret: <%= ENV["TWITTER_SECRET"]%>



# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"]%>
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"]%>
development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"]%>
